# Сообщение, которое выводится, когда игрок падает
fall-message: "Вы упали, чтобы встать восстановите свое здоровье."

# Количество хп, ниже которого нельзя опускаться(например ниже 10)
# P.S. хп и сердца это разное. 1 хп = 0.5 сердца
fall-health: 10.0
