name: KHealth
version: '${project.version}'
main: me.khealth.KHealth
api-version: 1.18
website: "https://discord.gg/JJx3HGwyqd"
authors: [Kelsi]
commands:
  sethealth:
    description: "Устанавливает здоровье игрока на указанное значение"
    usage: "/sethealth <игрок> <хп>\nПример: /sethealth KelsiDev 17.0"
    permission: khealth.health
    permission-message: У вас недостаточно прав!
